deploy:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnpv ./ ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - master
  environment:
    name: Default
    url: https://php.francescomasala.me

